### ISSUE TITLE
Getting dom-document-internal-entity in the middle of the text

### ISSUE THREAD

**Issue by mikeazores** [ivopetkov/html5-dom-document-php#40]
Hi!
I'm trying to get all h2 text using nodeValue from a dom document. **If the text contains some special characters**, I get html5-dom-document-internal-entity in the middle of the text.

For example, if the document contains this:
`....<h2>Anatom&iacute;a</h2>....`

I get in the nodeValue  = "Anatomdom-document-internal-entity&iacute;a"

I tried using both methods: $xpath->query("//h2") or $doc->querySelectorAll('h2')

If I use DomDocument it is working just fine and I get "Anatomía"

I'm using version 2.2.7 of HTML5DOMDocument.

Can this be a bug?

**Comment by ivopetkov** [comment]
Hi,
It's not a bug, but it's definitely not cool.
HTML5DOMDocument internally updates the DOM to preserve entities, white space, etc. and that's the reason you get 'dom-document-internal-entity'.
If you change `$node->nodeValue` with `$node->innerHTML` you will get the correct value.

**Comment by mikeazores** [comment]
Thank's, it did the trick. 👍

**Comment by Yiddishe-Kop** [comment]
And if you want only the textContent, use `getTextContent()` instead of `textContent`.

**Comment by achmizs** [comment]
Hello,

I am having the same problem, stuff like “html5-dom-document-internal-entity2-8217-end” in the middle of text. Using latest version (2.10).

Using `$node->innerHTML` is not an option because I need to get the text content of a text node (`DOMText`), which has no `innerHTML`. (Likewise there is no `getTextContent()`.) How can I do this? `textContent` and `wholeText` and `data` are all contaminated with the “internal-entity” stuff just like `nodeValue` is.
