### ISSUE TITLE
any loadHTML options for not adding a default doctype

### ISSUE THREAD

**Issue by shtse8** [ivopetkov/html5-dom-document-php#5]
as DOMDocument provide this options as follows:
```php
$document = new DOMDocument();
$doc->loadHTML($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD | LIBXML_COMPACT | LIBXML_NOENT );
```

I want to do the same thing, when there is missing DOCTYPE, don't add it, any advise?

**Comment by ivopetkov** [comment]
I'll check if the DOMDocument options can be supported in HTML5DOMDocument (I think there will be some issues).
Meanwhile you can use
```php
echo $dom->querySelector('html')->outerHTML;
echo $dom->querySelector('body')->outerHTML;
```

**Comment by shtse8** [comment]
The main problem is that I cannot detect if this a fragment or document passing after creating the object.

**Comment by WilliamStam** [comment]
also have this issue at the moment. using it to render and change some html for either page parts or entire pages. short of writing an if template contains <html> then echo $dom->querySelector('html')->outerHTML; else echo $dom->querySelector('body')->innerHTML; which could be messy.. is there any way to find out if the parser is going to add the html / body tags or not ? cause then i could use that instead for the if instead of the if template part

**Comment by WilliamStam** [comment]
guess i could just use the code used in the library 📦 
````
if ($template !== '' && preg_match('/\<!DOCTYPE.*?\>/', $template) === 0 && preg_match('/\<html.*?\>/', $template) === 0 && preg_match('/\<body.*?\>/', $template) === 0 && preg_match('/\<head.*?\>/', $template) === 0) {
	$content = $dom->querySelector('body')->innerHTML;
} else {
	$content = $dom->querySelector('html')->outerHTML;
}


````

**Comment by ivopetkov** [comment]
Hi, I'm glad to inform you that v1.0.0 of the library is released and it now supports the LIBXML_HTML_NOIMPLIED and LIBXML_HTML_NODEFDTD options.
